# Generated by Django 2.2.5 on 2019-09-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalCitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=1000)),
                ('journal_title', models.CharField(max_length=1000)),
                ('journal_volume', models.IntegerField(max_length=100)),
                ('journal_issue_number', models.IntegerField(max_length=100)),
                ('doi', models.CharField(max_length=1000, unique=True)),
                ('date_published', models.DateTimeField(max_length=1000)),
            ],
        ),
    ]
