# Generated by Django 2.2.5 on 2019-09-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalcitation',
            name='date_published',
            field=models.DateField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='journalcitation',
            name='journal_issue_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='journalcitation',
            name='journal_volume',
            field=models.IntegerField(),
        ),
    ]
